{
 "title": "Write throughput benchmark",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Benchmark",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true
  },
  {
   "title": "Incomming requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum by (resource,  subresource, verb, scope) (rate(apiserver_request_total{resource=\"pods\", verb=\"PATCH\", subresource!=\"\"}[1m]))",
     "legendFormat": "{{resource}}/{{subresource}} {{verb}}"
    },
    {
     "expr": "sum by (resource,  subresource, verb, scope) (rate(apiserver_request_total{resource=\"pods\", verb=\"PATCH\", subresource=\"\"}[1m]))",
     "legendFormat": "{{resource}} {{verb}}"
    }
   ]
  },
  {
   "title": "Opened watches",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (resource)(apiserver_longrunning_requests{verb=\"WATCH\", resource=\"pods\"})",
     "legendFormat": "{{resource}}"
    }
   ]
  },
  {
   "title": "Conflict rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by (storage, resource) (rate(apiserver_storage_update_conflicts_total{resource=\"pods\"}[1m]))",
     "legendFormat": "{{storage}} {{resouce}}"
    }
   ]
  },
  {
   "title": "Successfully handled reqeusts",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum by (resource, verb, subresource, code) (rate(apiserver_request_total{resource=\"pods\", verb=\"PATCH\", code=~\"2..\", subresource!=\"\"}[1m]))",
     "legendFormat": "{{resource}}/{{subresource}} {{verb}}"
    },
    {
     "expr": "sum by (resource, verb, subresource, code) (rate(apiserver_request_total{resource=\"pods\", verb=\"PATCH\", code=~\"2..\", subresource=\"\"}[1m]))",
     "legendFormat": "{{resource}} {{verb}}"
    }
   ]
  },
  {
   "title": "Watch termination rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(apiserver_terminated_watchers_total{resource=\"pods\"}[1m])",
     "legendFormat": "{{resource}} {{reason}}"
    }
   ]
  },
  {
   "title": "Write amplification",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apiserver_storage_update_attempts_sum{resource=\"pods\"}[1m])) by (storage, reource)\n/\nsum(rate(apiserver_storage_update_attempts_count{resource=\"pods\"}[1m])) by (storage, reource)",
     "legendFormat": "{{storage}} {{resource}}"
    }
   ]
  },
  {
   "title": "Error rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (resource, verb, code) (rate(apiserver_request_total{resource=\"pods\", verb=\"PATCH\", code!~\"2..\", subresource=\"\"}[1m]))\n/ ignoring(code) group_left\nsum by (resource, verb) (rate(apiserver_request_total{resource=\"pods\", verb=\"PATCH\", subresource=\"\"}[1m]))",
     "legendFormat": "{{resource}} {{verb}} {{code}} "
    },
    {
     "expr": "sum by (resource, verb, subresource, code) (rate(apiserver_request_total{resource=\"pods\", verb=\"PATCH\", code!~\"2..\", subresource!=\"\"}[1m]))\n/ ignoring(code) group_left\nsum by (resource, verb, subresource) (rate(apiserver_request_total{resource=\"pods\", verb=\"PATCH\", subresource!=\"\"}[1m]))",
     "legendFormat": "{{resource}}/{{subresource}} {{verb}} {{code}}"
    }
   ]
  },
  {
   "title": "Watch event dispatched",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 17 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(apiserver_watch_cache_events_dispatched_total{resource=\"pods\"}[1m])",
     "legendFormat": "{{resource}}"
    }
   ]
  },
  {
   "title": "APIServer Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 17 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(apiserver_request_duration_seconds_bucket{resource=\"pods\",verb=\"PATCH\",subresource=\"\"}[1m])) by (resource,  subresource, verb, scope, le))",
     "legendFormat": "{{resource}} {{verb}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(apiserver_request_duration_seconds_bucket{resource=\"pods\",verb=\"PATCH\",subresource!=\"\"}[1m])) by (resource,  subresource, verb, scope, le))",
     "legendFormat": "{{resource}}/{{subresource}} {{verb}}"
    }
   ]
  },
  {
   "title": "Watch data rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 25 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum by (resource) (rate(apiserver_watch_events_sizes_sum{resource=\"pods\"}[1m]))",
     "legendFormat": "{{resource}}"
    }
   ]
  },
  { "title": "Watch Delay", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "API server watch event dispatch P99 time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(apiserver_watch_events_dispatch_duration_seconds_bucket{resource=\"pods\",stage!=\"total\"}[1m])) by (resource, stage, le))",
     "legendFormat": "{{resource}} {{stage}}"
    }
   ]
  },
  {
   "title": "API server watch cache delay",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 34 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "((scalar(max(etcd_debugging_mvcc_current_revision)) - max by (resource) (apiserver_watch_cache_resource_version{resource=\"pods\"})) / scalar(max(deriv(etcd_debugging_mvcc_current_revision[15s])) > 0))",
     "legendFormat": "{{resource}}"
    }
   ]
  },
  {
   "title": "Watch cache read wait P99",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 34 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(apiserver_watch_cache_read_wait_seconds_bucket{resource=\"pods\"}[1m]))",
     "legendFormat": "{{resource}}"
    }
   ]
  },
  {
   "title": "Informer queued Items",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "informer_queued_items{resource=\"pods\"}",
     "legendFormat": "{{resource}} {{endpoint}}"
    }
   ]
  },
  {
   "title": "Informer processing delay",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 42 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(informer_processing_latency_seconds_bucket{resource=\"pods\"}[1m])) by (resource, endpoint, le))",
     "legendFormat": "{{resource}} {{endpoint}}"
    }
   ]
  },
  {
   "title": "Informer delay",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 42 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "((scalar(max(etcd_debugging_mvcc_current_revision)) - max by (resource, name) (informer_store_resource_version{resource=\"pods\"})) / scalar(max(deriv(etcd_debugging_mvcc_current_revision[30s])) > 0))",
     "legendFormat": "{{name}} {{resource}}"
    }
   ]
  },
  { "title": "Go runtime", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "Go scheduler latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(go_sched_latencies_seconds_bucket{endpoint!=\"http\"}[1m])) by (endpoint, le))",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Runnable Goroutines",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 51 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(go_sched_goroutines_runnable_goroutines) by (endpoint)",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Mutex wait time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 51 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(rate(go_sync_mutex_wait_total_seconds_total{endpoint!=\"http\"}[1m])) by (endpoint)",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "GC total duration time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(go_cpu_classes_gc_total_cpu_seconds_total[1m])",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "GC mark assist duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 59 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(go_cpu_classes_gc_mark_assist_cpu_seconds_total[1m])",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "User CPU seconds",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 59 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(go_cpu_classes_user_cpu_seconds_total[1m])",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  { "title": "Resource usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 } },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 68 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "max by (pod) (rate(container_cpu_usage_seconds_total{exported_namespace=\"kube-system\",container!=\"\"}[1m]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 68 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "max by (pod) (container_memory_working_set_bytes{exported_namespace=\"kube-system\",container!=\"\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Etcd", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 76 } },
  {
   "title": "Etcd client latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 77 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (resource, operation, le) (rate(etcd_request_duration_seconds_bucket{resource=\"pods\"}[1m])))",
     "legendFormat": "p99 {{resource}} {{operation}}"
    }
   ]
  },
  {
   "title": "Object count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 77 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max by (resource) (apiserver_resource_objects{resource=\"pods\"})",
     "legendFormat": "{{resource}}"
    }
   ]
  },
  {
   "title": "Etcd size",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 77 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "etcd_mvcc_db_total_size_in_bytes",
     "legendFormat": "total"
    },
    {
     "expr": "etcd_mvcc_db_total_size_in_use_in_bytes",
     "legendFormat": "usage"
    },
    {
     "expr": "etcd_server_quota_backend_bytes\n",
     "legendFormat": "quota"
    }
   ]
  },
  {
   "title": "Etcd server latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 86 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (type,le) (rate(etcd_server_request_duration_seconds_bucket[1m])))",
     "legendFormat": "p99 {{type}}"
    }
   ]
  },
  {
   "title": "Etcd server request rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 86 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(etcd_server_request_duration_seconds_count[1m])) by(type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Resource Size",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 86 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "max by (resource) (apiserver_resource_size_estimate_bytes{resource=\"pods\"})",
     "legendFormat": "{{resource}}"
    }
   ]
  }
 ]
}