kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
featureGates:
  "DetectCacheInconsistency": false
  "ConcurrentWatchObjectDecode": false
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: ClusterConfiguration
    etcd:
      local:
        extraArgs:
          quota-backend-bytes: "20000000000" # 20GB
          # client-cert-auth: "false"
          # cert-file: ""
          # key-file: ""
          # trusted-ca-file: ""
          # auto-tls: "true"
    apiServer:
      extraArgs:
        max-requests-inflight: "640"
        max-mutating-requests-inflight: "0"
        v: "4"
        # etcd-cafile: ""
        # etcd-certfile: ""
        # etcd-keyfile: ""
    controllerManager:
      extraArgs:
        bind-address: "0.0.0.0"
        authorization-always-allow-paths: "/healthz,/readyz,/livez,/metrics,/debug/pprof/profile,/debug/pprof/block,/debug/pprof/mutex"
        kube-api-qps: "500"
        kube-api-burst: "500"
        profiling: "true"
        v: "2"
        concurrent-deployment-syncs: "50"
        concurrent-daemonset-syncs: "50"
        concurrent-job-syncs: "50"
        concurrent-replicaset-syncs: "50"
        concurrent-statefulset-syncs: "50"
        concurrent-gc-syncs: "100"
        contention-profiling: "true"
        allocate-node-cidrs: "true" # KWOK needs false
    scheduler:
      extraArgs:
        bind-address: "0.0.0.0"
        authorization-always-allow-paths: "/healthz,/readyz,/livez,/metrics"
        kube-api-qps: "500"
        kube-api-burst: "500"
        profiling: "true"
        v: "3"


- role: worker
- role: worker
- role: worker
- role: worker
- role: worker
- role: worker
- role: worker
- role: worker
- role: worker
- role: worker
